# Generated by Django 6.1.1 on 2026-09-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('hire_date', models.DateField()),
                ('employment_status', models.BooleanField(default=False)),
                ('contract_type', models.CharField(max_length=100)),
                ('contract_start_date', models.DateField()),
                ('contract_end_date', models.DateField()),
                ('basic_salary', models.IntegerField()),
                ('currency_code', models.CharField(max_length=3)),
            ],
        ),
    ]
