# Generated by Django 6.1.1 on 2026-09-21 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='AttendanceRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('schedule_start_date', models.DateField()),
                ('schedule_end_date', models.DateField()),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('late_minutes', models.IntegerField()),
                ('early_departure', models.IntegerField()),
                ('overtime_minutes', models.IntegerField()),
                ('notes', models.TextField()),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
        ),
    ]
