# Generated by Django 6.1.1 on 2026-09-22 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancerecords',
            old_name='schedule_end_date',
            new_name='working_end',
        ),
        migrations.RenameField(
            model_name='attendancerecords',
            old_name='schedule_start_date',
            new_name='working_start',
        ),
        migrations.RemoveField(
            model_name='attendancerecords',
            name='early_departure',
        ),
    ]
