# Generated by Django 6.1.1 on 2026-09-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(max_length=100)),
                ('min_service_years', models.IntegerField()),
                ('max_service_years', models.IntegerField()),
                ('days_per_year', models.IntegerField()),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField()),
                ('allow_carry', models.BooleanField()),
                ('max_allow_carry', models.IntegerField()),
                ('accrual_method', models.CharField(max_length=100)),
                ('notes', models.TextField()),
            ],
        ),
    ]
