# Generated by Django 6.1.1 on 2026-09-22 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policy',
            old_name='max_allow_carry',
            new_name='carry_forward_amount',
        ),
        migrations.RenameField(
            model_name='policy',
            old_name='max_service_years',
            new_name='service_years',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='accrual_method',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='effective_from',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='effective_to',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='min_service_years',
        ),
    ]
